# run groovy file

groovy groovy/calculate_actual_score_gce.groovy;
groovy groovy/calculate_predicted_actual_score_gce.groovy;
groovy groovy/calculate_actual_score_ibd_42.groovy;
groovy groovy/calculate_actual_score_ibd_45.groovy;
groovy groovy/calculate_predicted_actual_score_ibd_42.groovy;
groovy groovy/calculate_predicted_actual_score_ibd_45.groovy;