# groovy calculate_actual_score_gce.groovy;calculate_predicted_actual_score_gce.groovy;calculate_score_gce.groovy

groovy groovy/calculate_actual_score_gce.groovy;
groovy groovy/calculate_predicted_actual_score_gce.groovy;
groovy groovy/calculate_score_gce.groovy;